services:
  fastapi-service:
    build: .
    container_name: fastapi-baseline
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs