services:
  fastapi-service:
    build:
      context: .
      args:
        PORT: 8000
    container_name: search-avilov
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=UTC
    volumes:
      - ./logs:/app/logs